<?php

namespace App\Services;

use Illuminate\Support\Str;

class ReportPdfGenerator
{
    /**
     * Generate a professional, multi-page PDF document in pure PHP.
     *
     * @param  array<string, mixed>  $report
     */
    public static function generate(array $report, string $studioName = 'SprintStudio', string $senderName = 'Studio Member'): string
    {
        $generator = new self($report, $studioName, $senderName);

        return $generator->build();
    }

    private array $pages = [];

    public function __construct(
        private array $report,
        private string $studioName,
        private string $senderName
    ) {}

    public function build(): string
    {
        $this->pages = [];

        $title = $this->report['title'] ?? 'Performance Report';
        $scope = ucfirst($this->report['scope'] ?? 'Project');
        $completionRate = (int) ($this->report['completion_rate'] ?? 0);
        $totalTasks = (int) ($this->report['total_tasks'] ?? 0);
        $completedTasks = (int) ($this->report['completed_tasks'] ?? 0);
        $unfinishedTasks = (int) ($this->report['unfinished_tasks'] ?? 0);
        $overdueTasks = (int) ($this->report['overdue_tasks'] ?? 0);
        $plannedSp = (int) ($this->report['planned_story_points'] ?? 0);
        $completedSp = (int) ($this->report['completed_story_points'] ?? 0);

        $auditTasks = $this->report['audit_tasks'] ?? ($this->report['tasks_list'] ?? []);

        // ── PAGE 1: Executive KPI & Summary + Initial Tasks ──
        $page1Ops = [];

        // Header Background Banner
        $page1Ops[] = '0.06 0.09 0.16 rg'; // Slate-900
        $page1Ops[] = '0 732 595 110 re f';

        // Header Accent Stripe
        $page1Ops[] = '0.31 0.27 0.95 rg'; // Indigo-600
        $page1Ops[] = '0 728 595 4 re f';

        // Header Text
        $page1Ops[] = '1 1 1 rg';
        $page1Ops[] = 'BT /F2 9 Tf 40 812 Td ('.strtoupper($this->escapePdfText($this->studioName)).'  •  '.strtoupper($scope).' REPORT) Tj ET';
        $page1Ops[] = 'BT /F2 18 Tf 40 790 Td ('.$this->escapePdfText($title).') Tj ET';
        $page1Ops[] = '0.8 0.85 0.95 rg';
        $page1Ops[] = 'BT /F1 9 Tf 40 770 Td (Generated by '.$this->escapePdfText($this->senderName).'  •  '.date('F j, Y, g:i A').') Tj ET';

        if (! empty($this->report['sprint_name'])) {
            $page1Ops[] = 'BT /F1 8.5 Tf 40 754 Td (Sprint: '.$this->escapePdfText($this->report['sprint_name']).'  •  Duration: '.$this->escapePdfText(($this->report['start_date'] ?? '').' to '.($this->report['end_date'] ?? '')).') Tj ET';
        }

        // Section Title: Executive KPI Summary
        $page1Ops[] = '0.06 0.09 0.16 rg';
        $page1Ops[] = 'BT /F2 12 Tf 40 695 Td (EXECUTIVE SUMMARY & KEY METRICS) Tj ET';

        // 4 KPI Metric Boxes (x, y, w, h)
        // Box 1: Overall Completion Rate
        $page1Ops = array_merge($page1Ops, $this->renderKpiBox(40, 615, 120, 65, 'COMPLETION RATE', "{$completionRate}%", '0.31 0.27 0.95'));

        // Box 2: Tasks Completed
        $page1Ops = array_merge($page1Ops, $this->renderKpiBox(175, 615, 120, 65, 'TASKS COMPLETED', "{$completedTasks} / {$totalTasks}", '0.06 0.09 0.16'));

        // Box 3: Story Points Burned
        $page1Ops = array_merge($page1Ops, $this->renderKpiBox(310, 615, 120, 65, 'STORY POINTS', "{$completedSp} / {$plannedSp} pts", '0.06 0.09 0.16'));

        // Box 4: Unfinished & Overdue
        $alertColor = $overdueTasks > 0 ? '0.88 0.11 0.28' : '0.85 0.47 0.02';
        $page1Ops = array_merge($page1Ops, $this->renderKpiBox(445, 615, 110, 65, 'UNFINISHED / LATE', "{$unfinishedTasks} ({$overdueTasks} late)", $alertColor));

        // Audit Table Section Header
        $page1Ops[] = '0.06 0.09 0.16 rg';
        $page1Ops[] = 'BT /F2 11 Tf 40 580 Td (DETAILED TASK AUDIT LOG) Tj ET';

        // Table Header (y = 555)
        $currentY = 555;
        $page1Ops = array_merge($page1Ops, $this->renderTableHeader($currentY));
        $currentY -= 20;

        // Render first page rows (up to 18 rows)
        $rowsPerPage1 = 18;
        $page1Tasks = array_slice($auditTasks, 0, $rowsPerPage1);
        $remainingTasks = array_slice($auditTasks, $rowsPerPage1);

        $rowIdx = 0;
        foreach ($page1Tasks as $t) {
            $isEven = ($rowIdx % 2 === 0);
            $page1Ops = array_merge($page1Ops, $this->renderTableRow($t, $currentY, $isEven));
            $currentY -= 22;
            $rowIdx++;
        }

        if (empty($page1Tasks)) {
            $page1Ops[] = '0.5 0.55 0.65 rg';
            $page1Ops[] = 'BT /F1 9 Tf 40 530 Td (No tasks recorded for this report scope.) Tj ET';
        }

        // Footer on Page 1
        $page1Ops[] = $this->renderFooter(1);
        $this->pages[] = implode("\n", $page1Ops);

        // ── SUBSEQUENT PAGES (if many tasks) ──
        $chunkSize = 26;
        $subsequentChunks = array_chunk($remainingTasks, $chunkSize);
        $pageNum = 2;

        foreach ($subsequentChunks as $chunk) {
            $pageOps = [];
            // Compact Header
            $pageOps[] = '0.06 0.09 0.16 rg';
            $pageOps[] = '0 780 595 62 re f';
            $pageOps[] = '0.31 0.27 0.95 rg';
            $pageOps[] = '0 776 595 4 re f';

            $pageOps[] = '1 1 1 rg';
            $pageOps[] = 'BT /F2 12 Tf 40 812 Td ('.$this->escapePdfText($title).' (Continued)) Tj ET';
            $pageOps[] = '0.8 0.85 0.95 rg';
            $pageOps[] = 'BT /F1 8.5 Tf 40 792 Td (Task Audit Breakdown  •  Page '.$pageNum.') Tj ET';

            $subY = 745;
            $pageOps = array_merge($pageOps, $this->renderTableHeader($subY));
            $subY -= 20;

            $sIdx = 0;
            foreach ($chunk as $t) {
                $isEven = ($sIdx % 2 === 0);
                $pageOps = array_merge($pageOps, $this->renderTableRow($t, $subY, $isEven));
                $subY -= 22;
                $sIdx++;
            }

            $pageOps[] = $this->renderFooter($pageNum);
            $this->pages[] = implode("\n", $pageOps);
            $pageNum++;
        }

        return $this->compilePdf();
    }

    private function renderKpiBox(int $x, int $y, int $w, int $h, string $label, string $val, string $valColor): array
    {
        $ops = [];
        // Fill
        $ops[] = '0.97 0.98 0.99 rg';
        $ops[] = "{$x} {$y} {$w} {$h} re f";
        // Border
        $ops[] = '0.88 0.91 0.94 RG 1 w';
        $ops[] = "{$x} {$y} {$w} {$h} re s";

        // Label
        $ops[] = '0.45 0.50 0.60 rg';
        $ops[] = 'BT /F2 7 Tf '.($x + 10).' '.($y + $h - 18).' Td ('.$this->escapePdfText($label).') Tj ET';

        // Value
        $ops[] = "{$valColor} rg";
        $ops[] = 'BT /F2 14 Tf '.($x + 10).' '.($y + 14).' Td ('.$this->escapePdfText($val).') Tj ET';

        return $ops;
    }

    private function renderTableHeader(int $y): array
    {
        $ops = [];
        // Background
        $ops[] = '0.92 0.94 0.97 rg';
        $ops[] = "40 {$y} 515 18 re f";
        $ops[] = '0.80 0.85 0.90 RG 0.5 w';
        $ops[] = "40 {$y} 515 18 re s";

        // Columns text
        $ops[] = '0.2 0.25 0.35 rg';
        $ops[] = 'BT /F2 8 Tf 46 '.($y + 5).' Td (ID) Tj ET';
        $ops[] = 'BT /F2 8 Tf 80 '.($y + 5).' Td (TASK TITLE) Tj ET';
        $ops[] = 'BT /F2 8 Tf 270 '.($y + 5).' Td (ASSIGNEE) Tj ET';
        $ops[] = 'BT /F2 8 Tf 390 '.($y + 5).' Td (STATUS) Tj ET';
        $ops[] = 'BT /F2 8 Tf 460 '.($y + 5).' Td (DEADLINE) Tj ET';
        $ops[] = 'BT /F2 8 Tf 520 '.($y + 5).' Td (SP) Tj ET';

        return $ops;
    }

    private function renderTableRow(array $task, int $y, bool $isEven): array
    {
        $ops = [];
        // Row background
        if ($isEven) {
            $ops[] = '0.98 0.98 0.99 rg';
            $ops[] = "40 {$y} 515 20 re f";
        }
        // Bottom border line
        $ops[] = '0.90 0.92 0.95 RG 0.5 w';
        $ops[] = "40 {$y} m 555 {$y} l S";

        $taskId = '#'.($task['id'] ?? '0');
        $title = Str::limit($task['title'] ?? 'Untitled Task', 36);
        $assignee = Str::limit($task['assigned_employee'] ?? ($task['assignee'] ?? 'Unassigned'), 20);
        $status = ucfirst(str_replace('_', ' ', $task['status'] ?? 'todo'));
        $deadline = ! empty($task['deadline']) ? date('M j', strtotime($task['deadline'])) : '—';
        $sp = ($task['final_sp'] ?? ($task['original_sp'] ?? ($task['estimated_hours'] ?? 0))).' pts';

        $ops[] = '0.4 0.45 0.55 rg';
        $ops[] = 'BT /F1 8 Tf 46 '.($y + 6).' Td ('.$this->escapePdfText($taskId).') Tj ET';

        $ops[] = '0.1 0.15 0.25 rg';
        $ops[] = 'BT /F2 8 Tf 80 '.($y + 6).' Td ('.$this->escapePdfText($title).') Tj ET';

        $ops[] = '0.3 0.35 0.45 rg';
        $ops[] = 'BT /F1 8 Tf 270 '.($y + 6).' Td ('.$this->escapePdfText($assignee).') Tj ET';

        // Status color
        if ($task['status'] === 'completed') {
            $ops[] = '0.06 0.6 0.35 rg';
        } elseif ($task['on_time_status'] === 'Overdue') {
            $ops[] = '0.85 0.1 0.25 rg';
        } else {
            $ops[] = '0.2 0.4 0.8 rg';
        }
        $ops[] = 'BT /F2 7.5 Tf 390 '.($y + 6).' Td ('.$this->escapePdfText($status).') Tj ET';

        $ops[] = '0.4 0.45 0.55 rg';
        $ops[] = 'BT /F1 8 Tf 460 '.($y + 6).' Td ('.$this->escapePdfText($deadline).') Tj ET';

        $ops[] = '0.1 0.15 0.25 rg';
        $ops[] = 'BT /F2 8 Tf 520 '.($y + 6).' Td ('.$this->escapePdfText($sp).') Tj ET';

        return $ops;
    }

    private function renderFooter(int $pageNum): string
    {
        $escapedStudio = $this->escapePdfText($this->studioName);

        return implode("\n", [
            '0.60 0.65 0.72 rg',
            'BT /F1 7.5 Tf 40 28 Td (SprintStudio SaaS  •  '.$escapedStudio.'  •  Confidential Performance Report) Tj ET',
            'BT /F1 7.5 Tf 510 28 Td (Page '.$pageNum.') Tj ET',
        ]);
    }

    private function escapePdfText(string $str): string
    {
        // Replace non-ASCII and escape special PDF characters
        $str = iconv('UTF-8', 'Windows-1252//TRANSLIT', $str) ?: $str;
        $str = str_replace('\\', '\\\\', $str);
        $str = str_replace('(', '\(', $str);
        $str = str_replace(')', '\)', $str);

        return $str;
    }

    private function compilePdf(): string
    {
        $numPages = count($this->pages);
        $font1Obj = 1;
        $font2Obj = 2;
        $catalogObj = 3;
        $pagesObj = 4;

        $nextObjId = 5;
        $pageObjIds = [];
        $streamObjIds = [];

        for ($i = 0; $i < $numPages; $i++) {
            $pageObjIds[] = $nextObjId++;
            $streamObjIds[] = $nextObjId++;
        }

        $out = "%PDF-1.4\n";
        $offsets = [];

        // Font 1 (Helvetica)
        $offsets[$font1Obj] = strlen($out);
        $out .= "{$font1Obj} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj\n";

        // Font 2 (Helvetica-Bold)
        $offsets[$font2Obj] = strlen($out);
        $out .= "{$font2Obj} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>\nendobj\n";

        // Catalog
        $offsets[$catalogObj] = strlen($out);
        $out .= "{$catalogObj} 0 obj\n<< /Type /Catalog /Pages {$pagesObj} 0 R >>\nendobj\n";

        // Pages root
        $kidsStr = implode(' 0 R ', $pageObjIds).' 0 R';
        $offsets[$pagesObj] = strlen($out);
        $out .= "{$pagesObj} 0 obj\n<< /Type /Pages /Kids [{$kidsStr}] /Count {$numPages} >>\nendobj\n";

        // Pages & Streams
        for ($i = 0; $i < $numPages; $i++) {
            $pId = $pageObjIds[$i];
            $sId = $streamObjIds[$i];
            $stream = $this->pages[$i];
            $sLen = strlen($stream);

            $offsets[$pId] = strlen($out);
            $out .= "{$pId} 0 obj\n<< /Type /Page /Parent {$pagesObj} 0 R /MediaBox [0 0 595 842] /Contents {$sId} 0 R /Resources << /Font << /F1 {$font1Obj} 0 R /F2 {$font2Obj} 0 R >> >> >>\nendobj\n";

            $offsets[$sId] = strlen($out);
            $out .= "{$sId} 0 obj\n<< /Length {$sLen} >>\nstream\n{$stream}\nendstream\nendobj\n";
        }

        $xrefOffset = strlen($out);
        $totalObjs = $nextObjId;
        $out .= "xref\n0 {$totalObjs}\n";
        $out .= "0000000000 65535 f \n";
        for ($i = 1; $i < $totalObjs; $i++) {
            $out .= sprintf("%010d 00000 n \n", $offsets[$i]);
        }

        $out .= "trailer\n<< /Size {$totalObjs} /Root {$catalogObj} 0 R >>\nstartxref\n{$xrefOffset}\n%%EOF";

        return $out;
    }
}
