import React, { useState } from 'react';
import { Head, usePage, useForm } from '@inertiajs/react';
import TenantLayout from '@/Layouts/TenantLayout';
import { FileText, Archive, Download, Trash2, Calendar, User, FolderKanban, PlusCircle, CheckCircle2, ChevronRight, HelpCircle } from 'lucide-react';
import ApplicationLogo from '@/Components/ApplicationLogo';

export default function Docs({ studio, projects = [], members = [], reports = [] }) {
    const { activeWorkspace } = usePage().props;
    const [activeTab, setActiveTab] = useState('handbook');
    const [activePrintReport, setActivePrintReport] = useState(null);

    const downloadCsvReport = (report) => {
        const csvRows = [];
        csvRows.push(['VAULTERA LABS - PIPELINE REPORT']);
        csvRows.push(['Report Name', report.name]);
        csvRows.push(['Scope Type', report.type.toUpperCase()]);
        csvRows.push(['Target Name', report.target_name]);
        csvRows.push(['Generated By', report.created_by]);
        csvRows.push(['Date Generated', new Date(report.created_at).toLocaleString()]);
        csvRows.push([]);

        // Metrics
        csvRows.push(['METRICS SUMMARY']);
        csvRows.push(['Total Tasks', report.metrics?.total_tasks ?? 0]);
        csvRows.push(['Completed Tasks', report.metrics?.completed_tasks ?? 0]);
        if (report.metrics?.completion_rate !== undefined) {
            csvRows.push(['Completion Rate', `${report.metrics.completion_rate}%`]);
        }
        if (report.metrics?.critical_tasks !== undefined) {
            csvRows.push(['Critical Path Tasks', report.metrics.critical_tasks]);
        }
        csvRows.push([]);

        // Task List
        const tasks = report.metrics?.tasks_list || [];
        if (tasks.length > 0) {
            csvRows.push(['TASK BREAKDOWN']);
            csvRows.push(['Task ID', 'Title', 'Status', 'Priority', 'Hours', 'Assignee', 'Is Critical']);
            tasks.forEach(t => {
                csvRows.push([
                    t.id,
                    t.title,
                    t.status,
                    t.priority || 'Medium',
                    t.estimated_hours || 0,
                    t.assignee || 'Unassigned',
                    t.is_critical ? 'Yes' : 'No'
                ]);
            });
        }

        const csvContent = csvRows.map(e => e.map(val => `"${String(val).replace(/"/g, '""')}"`).join(',')).join('\n');
        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.setAttribute('href', url);
        link.setAttribute('download', `${report.name.toLowerCase().replace(/[^a-z0-9]/gi, '_')}.csv`);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    // Report generation form state
    const { data, setData, post, processing, reset, errors } = useForm({
        name: '',
        type: 'project',
        target_id: '',
        date_range: {
            start: new Date().toISOString().slice(0, 10),
            end: new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10),
        }
    });

    const handleGenerateReport = (e) => {
        e.preventDefault();
        
        // Auto name if empty
        let defaultName = data.name;
        if (!defaultName) {
            const scopeTarget = data.type === 'project' 
                ? (projects.find(p => String(p.id) === String(data.target_id))?.name || 'Workspace')
                : data.type === 'team'
                ? (members.find(m => String(m.id) === String(data.target_id))?.name || 'Member')
                : `${data.date_range.start}_to_${data.date_range.end}`;
            
            defaultName = `${data.type.toUpperCase()}_Report_${scopeTarget}_${new Date().toISOString().slice(0, 10)}`;
        }

        post(route('tenant.docs.archive', { tenant: activeWorkspace }), {
            data: { ...data, name: defaultName },
            onSuccess: () => {
                reset('name');
            }
        });
    };

    const handleDeleteReport = (reportId) => {
        if (confirm('Are you sure you want to delete this archived report? This cannot be undone.')) {
            // Delete report
            useForm().delete(route('tenant.docs.archive.delete', { tenant: activeWorkspace, report: reportId }));
        }
    };

    const triggerDownload = (report) => {
        const jsonString = `data:text/json;charset=utf-8,${encodeURIComponent(
            JSON.stringify(report, null, 2)
        )}`;
        const downloadAnchor = document.createElement('a');
        downloadAnchor.setAttribute('href', jsonString);
        downloadAnchor.setAttribute('download', `${report.name.toLowerCase().replace(/[^a-z0-9]/gi, '_')}.json`);
        document.body.appendChild(downloadAnchor);
        downloadAnchor.click();
        downloadAnchor.remove();
    };

    const downloadPdfDirectly = (report) => {
        const element = document.getElementById('print-area');
        if (!element) return;

        const executeDownload = () => {
            const opt = {
                margin:       [0.4, 0.4, 0.4, 0.4],
                filename:     `${report.name.toLowerCase().replace(/[^a-z0-9]/gi, '_')}.pdf`,
                image:        { type: 'jpeg', quality: 0.98 },
                html2canvas:  { 
                    scale: 2, 
                    useCORS: true, 
                    logging: false, 
                    windowWidth: 794,
                    scrollX: 0,
                    scrollY: 0,
                    x: 0,
                    y: 0
                },
                jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' },
                pagebreak:    { mode: ['avoid-all', 'css', 'legacy'] }
            };
            window.html2pdf().set(opt).from(element).save();
        };

        if (window.html2pdf) {
            executeDownload();
        } else {
            const script = document.createElement('script');
            script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';
            script.onload = executeDownload;
            document.head.appendChild(script);
        }
    };


    return (
        <TenantLayout>
            <Head title="Documentation & Archiving — StudioSprint" />

            <div className="flex-1 overflow-y-auto bg-slate-50 dark:bg-slate-950 p-6 sm:p-10 select-none">
                <div className="max-w-6xl mx-auto space-y-6">
                    
                    {/* Header */}
                    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                        <div>
                            <h1 className="font-heading text-2xl font-extrabold text-gray-900 dark:text-slate-100 tracking-tight">
                                Docs & Report Archiving
                            </h1>
                            <p className="font-sans text-xs text-slate-500 dark:text-slate-400 mt-1">
                                Access developer handbooks, platform specs, and generate/archive compliance and sprint velocity reports.
                            </p>
                        </div>

                        {/* Tabs switch */}
                        <div className="flex rounded-xl bg-gray-200/80 p-1 dark:bg-slate-800/80 shrink-0 self-start">
                            <button
                                onClick={() => setActiveTab('handbook')}
                                className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-xs font-bold transition-all ${
                                    activeTab === 'handbook'
                                        ? 'bg-white text-indigo-600 shadow-sm dark:bg-slate-700 dark:text-indigo-300'
                                        : 'text-gray-500 hover:text-gray-800 dark:text-slate-400 dark:hover:text-slate-200'
                                }`}
                            >
                                <FileText className="w-3.5 h-3.5" />
                                Handbook & Specs
                            </button>
                            <button
                                onClick={() => setActiveTab('archive')}
                                className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-xs font-bold transition-all ${
                                    activeTab === 'archive'
                                        ? 'bg-white text-indigo-600 shadow-sm dark:bg-slate-700 dark:text-indigo-300'
                                        : 'text-gray-500 hover:text-gray-800 dark:text-slate-400 dark:hover:text-slate-200'
                                }`}
                            >
                                <Archive className="w-3.5 h-3.5" />
                                Report Archiving
                            </button>
                        </div>
                    </div>

                    {activeTab === 'handbook' && (
                        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                            {/* Left list */}
                            <div className="lg:col-span-2 space-y-6">
                                <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                                    <h2 className="text-base font-bold text-gray-900 dark:text-slate-100 flex items-center gap-2">
                                        <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                                        StudioSprint Platform Architecture Overview
                                    </h2>
                                    <p className="mt-3 text-xs text-gray-500 dark:text-slate-400 leading-relaxed font-sans">
                                        Welcome to StudioSprint. Our platform is structured as an integrated multi-tenant pipeline connecting deterministic scheduling calculations with modern deep-learning recommendation algorithms:
                                    </p>
                                    <div className="mt-4 space-y-3 font-sans text-xs text-slate-600 dark:text-slate-300">
                                        {[
                                            { title: 'Deterministic Critical Path Engine', desc: 'Schedules tasks relative to project release boundaries dynamically skipping weekends.' },
                                            { title: 'AI-Powered Developer Match Fit', desc: 'Predicts suitability score between developers and tasks using Graph Neural Network (GNN) embeddings.' },
                                            { title: 'Fast Cloud Inference', desc: 'Leverages cloud-hosted Groq API engines for fast natural language sprint breakdowns.' }
                                        ].map((item, idx) => (
                                            <div key={idx} className="flex gap-2 p-3 rounded-xl bg-slate-50 dark:bg-slate-800/40 border border-slate-100 dark:border-slate-800/50">
                                                <ChevronRight className="w-4 h-4 text-indigo-500 shrink-0 mt-0.5" />
                                                <div>
                                                    <span className="font-bold text-gray-800 dark:text-slate-200 block">{item.title}</span>
                                                    <span className="text-gray-500 dark:text-slate-400 mt-0.5 block">{item.desc}</span>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </section>

                                <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                                    <h2 className="text-base font-bold text-gray-900 dark:text-slate-100">
                                        Developer Onboarding Playbook
                                    </h2>
                                    <p className="mt-2 text-xs text-slate-600 dark:text-slate-400 font-sans leading-relaxed">
                                        Every new developer must complete onboarding via the central profile setup. Ensure that your weekly work capacity (hours) is updated regularly. This is critical for the AI resource allocator and Gantt scheduler to calculate healthy team sprint capacities.
                                    </p>
                                    <div className="mt-4 p-4 rounded-xl border-l-4 border-amber-500 bg-amber-500/5 text-amber-700 dark:text-amber-400 text-xs font-semibold font-sans">
                                        Looking to generate team schedules or project status reports? Check the "Report Archiving" tab at the top-right to output and archive complete metrics.
                                    </div>
                                </section>
                            </div>

                            {/* Right sidebar */}
                            <div className="space-y-6">
                                <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                                    <h3 className="text-xs font-extrabold uppercase tracking-wider text-gray-400">
                                        Need Help?
                                    </h3>
                                    <div className="mt-3 space-y-3 font-sans text-xs">
                                        {[
                                            'How do I add dependencies to tasks?',
                                            'What is task float slack?',
                                            'How do I export schedules?',
                                        ].map((q, idx) => (
                                            <a key={idx} href="#" className="flex items-center gap-2 text-slate-600 dark:text-slate-300 hover:text-indigo-500 transition-colors py-1.5 border-b border-gray-100 last:border-0 dark:border-slate-800">
                                                <HelpCircle className="w-3.5 h-3.5 text-slate-400" />
                                                <span className="truncate">{q}</span>
                                            </a>
                                        ))}
                                    </div>
                                </section>
                            </div>
                        </div>
                    )}

                    {activeTab === 'archive' && (
                        <div className="grid grid-cols-1 lg:grid-cols-[1.1fr_.9fr] gap-6">
                            {/* Generator Form */}
                            <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                                <div className="mb-5 flex items-center gap-2">
                                    <PlusCircle className="h-5 w-5 text-indigo-500" />
                                    <h2 className="text-base font-bold text-gray-900 dark:text-slate-100">
                                        Generate New Report
                                    </h2>
                                </div>
                                <form onSubmit={handleGenerateReport} className="space-y-4">
                                    <div>
                                        <label className="block text-xs font-bold text-gray-500 dark:text-slate-400 uppercase tracking-wider mb-1.5">
                                            Report Name (Optional)
                                        </label>
                                        <input
                                            type="text"
                                            value={data.name}
                                            onChange={e => setData('name', e.target.value)}
                                            placeholder="e.g. Q3_Sprint_Velocity_Report"
                                            className="w-full rounded-xl border border-gray-200 bg-gray-50 dark:bg-slate-800 dark:border-slate-700 p-3 text-xs outline-none focus:border-indigo-500 text-gray-900 dark:text-slate-100"
                                        />
                                    </div>

                                    <div className="grid grid-cols-2 gap-4">
                                        <div>
                                            <label className="block text-xs font-bold text-gray-500 dark:text-slate-400 uppercase tracking-wider mb-1.5">
                                                Report Scope
                                            </label>
                                            <select
                                                value={data.type}
                                                onChange={e => {
                                                    const typeVal = e.target.value;
                                                    setData(prev => {
                                                        const next = { ...prev, type: typeVal };
                                                        if (typeVal === 'project') {
                                                            next.target_id = projects[0]?.id || '';
                                                        } else if (typeVal === 'team') {
                                                            next.target_id = members[0]?.id || '';
                                                        } else {
                                                            next.target_id = '';
                                                        }
                                                        return next;
                                                    });
                                                }}
                                                className="w-full rounded-xl border border-gray-200 bg-gray-50 dark:bg-slate-800 dark:border-slate-700 p-3 text-xs outline-none focus:border-indigo-500 text-gray-900 dark:text-slate-100"
                                            >
                                                <option value="project">Project Status</option>
                                                <option value="team">Team Member Workload</option>
                                                <option value="schedule">Schedule / Date Range</option>
                                            </select>
                                        </div>

                                        <div>
                                            {data.type === 'project' && (
                                                <>
                                                    <label className="block text-xs font-bold text-gray-500 dark:text-slate-400 uppercase tracking-wider mb-1.5">
                                                        Select Project
                                                    </label>
                                                    <select
                                                        value={data.target_id}
                                                        onChange={e => setData('target_id', e.target.value)}
                                                        className="w-full rounded-xl border border-gray-200 bg-gray-50 dark:bg-slate-800 dark:border-slate-700 p-3 text-xs outline-none focus:border-indigo-500 text-gray-900 dark:text-slate-100"
                                                    >
                                                        <option value="">-- Choose Project --</option>
                                                        {projects.map(p => (
                                                            <option key={p.id} value={p.id}>{p.name}</option>
                                                        ))}
                                                    </select>
                                                </>
                                            )}

                                            {data.type === 'team' && (
                                                <>
                                                    <label className="block text-xs font-bold text-gray-500 dark:text-slate-400 uppercase tracking-wider mb-1.5">
                                                        Select Member
                                                    </label>
                                                    <select
                                                        value={data.target_id}
                                                        onChange={e => setData('target_id', e.target.value)}
                                                        className="w-full rounded-xl border border-gray-200 bg-gray-50 dark:bg-slate-800 dark:border-slate-700 p-3 text-xs outline-none focus:border-indigo-500 text-gray-900 dark:text-slate-100"
                                                    >
                                                        <option value="">-- Choose Member --</option>
                                                        {members.map(m => (
                                                            <option key={m.id} value={m.id}>{m.name}</option>
                                                        ))}
                                                    </select>
                                                </>
                                            )}
                                        </div>
                                    </div>

                                    {data.type === 'schedule' && (
                                        <div className="grid grid-cols-2 gap-4 p-4 rounded-xl bg-slate-50 dark:bg-slate-800/40 border border-slate-100 dark:border-slate-800/50">
                                            <div>
                                                <label className="block text-[10px] font-bold text-gray-400 dark:text-slate-500 uppercase tracking-wider mb-1">
                                                    Start Date
                                                </label>
                                                <input
                                                    type="date"
                                                    value={data.date_range.start}
                                                    onChange={e => setData('date_range', { ...data.date_range, start: e.target.value })}
                                                    className="w-full rounded-lg border border-gray-200 bg-white dark:bg-slate-800 dark:border-slate-700 px-3 py-2 text-xs outline-none focus:border-indigo-500 text-gray-900 dark:text-slate-100"
                                                />
                                            </div>
                                            <div>
                                                <label className="block text-[10px] font-bold text-gray-400 dark:text-slate-500 uppercase tracking-wider mb-1">
                                                    End Date
                                                </label>
                                                <input
                                                    type="date"
                                                    value={data.date_range.end}
                                                    onChange={e => setData('date_range', { ...data.date_range, end: e.target.value })}
                                                    className="w-full rounded-lg border border-gray-200 bg-white dark:bg-slate-800 dark:border-slate-700 px-3 py-2 text-xs outline-none focus:border-indigo-500 text-gray-900 dark:text-slate-100"
                                                />
                                            </div>
                                        </div>
                                    )}

                                    <button
                                        type="submit"
                                        disabled={processing}
                                        className="w-full inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 p-3 text-xs font-bold text-white shadow-sm transition-all"
                                    >
                                        <Archive className="w-4 h-4" />
                                        Generate & Archive
                                    </button>
                                </form>
                            </section>

                            {/* Reports Registry */}
                            <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900 flex flex-col min-h-[300px]">
                                <h2 className="text-base font-bold text-gray-900 dark:text-slate-100 mb-4 flex items-center gap-2">
                                    <Archive className="h-5 w-5 text-indigo-500" />
                                    Archived Reports Registry
                                </h2>

                                <div className="flex-1 overflow-auto space-y-3 font-sans">
                                    {reports.length ? reports.map(r => (
                                        <div key={r.id} className="p-4 rounded-xl border border-gray-100 dark:border-slate-800/80 bg-slate-50/50 dark:bg-slate-900/40 flex items-center justify-between gap-4">
                                            <div className="min-w-0 space-y-1">
                                                <p className="text-xs font-bold text-gray-900 dark:text-slate-100 truncate" title={r.name}>
                                                    {r.name}
                                                </p>
                                                <div className="flex flex-wrap items-center gap-x-2.5 gap-y-1 text-[10px] text-gray-400">
                                                    <span className="flex items-center gap-1">
                                                        {r.type === 'project' ? <FolderKanban className="w-3.5 h-3.5 text-indigo-500" /> : r.type === 'team' ? <User className="w-3.5 h-3.5 text-indigo-500" /> : <Calendar className="w-3.5 h-3.5 text-indigo-500" />}
                                                        <span className="font-semibold text-gray-600 dark:text-slate-300">{r.target_name}</span>
                                                    </span>
                                                    <span>•</span>
                                                    <span>By {r.created_by}</span>
                                                    <span>•</span>
                                                    <span>{new Date(r.created_at).toLocaleDateString()}</span>
                                                </div>

                                                {r.metrics && (
                                                    <div className="mt-2 flex items-center gap-3 text-[10px] text-slate-500 dark:text-slate-400">
                                                        <span>Tasks: <strong>{r.metrics.total_tasks ?? 0}</strong></span>
                                                        {r.metrics.completion_rate !== undefined && (
                                                            <span>Comp. Rate: <strong>{r.metrics.completion_rate}%</strong></span>
                                                        )}
                                                        {r.metrics.critical_tasks !== undefined && (
                                                            <span>Critical: <strong>{r.metrics.critical_tasks}</strong></span>
                                                        )}
                                                    </div>
                                                )}
                                            </div>

                                            <div className="flex items-center gap-1 shrink-0">
                                                <button
                                                    onClick={() => setActivePrintReport(r)}
                                                    className="px-3 py-1.5 rounded-lg border border-indigo-150 hover:border-indigo-300 text-indigo-600 hover:bg-indigo-50/50 dark:border-slate-800 dark:hover:bg-slate-700 transition-all text-[11px] font-bold"
                                                    title="Preview and Download PDF"
                                                >
                                                    View Report
                                                </button>
                                                <button
                                                    onClick={() => downloadCsvReport(r)}
                                                    className="p-2 rounded-lg text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 hover:text-slate-700 dark:hover:text-slate-200 transition-colors"
                                                    title="Download Excel (CSV)"
                                                >
                                                    <Download className="w-4 h-4" />
                                                </button>
                                                <button
                                                    onClick={() => handleDeleteReport(r.id)}
                                                    className="p-2 rounded-lg text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/20 hover:text-rose-600 transition-colors"
                                                    title="Delete Archived Report"
                                                >
                                                    <Trash2 className="w-4 h-4" />
                                                </button>
                                            </div>
                                        </div>
                                    )) : (
                                        <div className="h-full flex flex-col items-center justify-center text-center text-gray-400 py-10">
                                            <Archive className="w-8 h-8 text-gray-300 dark:text-slate-700 mb-2" />
                                            <p className="text-xs font-semibold">No reports generated yet</p>
                                            <p className="text-[10px] text-gray-500 mt-0.5">Use the generator on the left to archive a project or team report.</p>
                                        </div>
                                    )}
                                </div>
                            </section>
                        </div>
                    )}
                </div>
            </div>

            {activePrintReport && (
                <div className="fixed inset-0 bg-slate-900/60 z-[9999] flex items-center justify-center p-4 md:p-6 backdrop-blur-sm print:p-0 print:bg-white print:static print:inset-auto print:z-auto">
                    <div className="w-full max-w-4xl max-h-[90vh] bg-white dark:bg-slate-900 rounded-3xl shadow-2xl border border-gray-200 dark:border-slate-800 overflow-hidden flex flex-col justify-between print:max-h-none print:overflow-visible print:shadow-none print:border-none print:rounded-none">
                        
                        {/* Actions bar - hidden on print */}
                        <div className="flex items-center justify-between px-6 py-4 bg-gray-50 border-b border-gray-150/80 dark:bg-slate-800 dark:border-slate-800 print:hidden">
                            <span className="text-xs font-bold text-gray-500 dark:text-slate-400">Vaultera Labs Report Archive</span>
                            <div className="flex items-center gap-2">
                                <button
                                    onClick={() => downloadPdfDirectly(activePrintReport)}
                                    className="px-3.5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold shadow transition-all flex items-center gap-1.5"
                                >
                                    <Download className="w-3.5 h-3.5" />
                                    Download as PDF
                                </button>
                                <button
                                    onClick={() => downloadCsvReport(activePrintReport)}
                                    className="px-3.5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold shadow transition-all flex items-center gap-1.5"
                                >
                                    <Download className="w-3.5 h-3.5" />
                                    Download CSV (Excel)
                                </button>
                                <button
                                    onClick={() => setActivePrintReport(null)}
                                    className="px-3.5 py-2 rounded-xl border border-gray-200 dark:border-slate-700 hover:bg-gray-100 dark:hover:bg-slate-800 text-gray-600 dark:text-slate-300 text-xs font-bold transition-all"
                                >
                                    Close Preview
                                </button>
                            </div>
                        </div>

                        {/* Scrollable container for preview modal */}
                        <div className="overflow-y-auto flex-1 print:overflow-visible">
                            
                            {/* Printable Sheet */}
                            <div id="print-area" className="w-full max-w-[794px] mx-auto p-8 md:p-12 space-y-8 bg-white text-slate-900 font-sans print:p-0 box-border">
                            {/* CSS styles to hide rest of page on print */}
                            <style>{`
                                @media print {
                                    body > * {
                                        display: none !important;
                                    }
                                    html, body {
                                        background: #fff !important;
                                        color: #000 !important;
                                    }
                                    #print-area, #print-area * {
                                        display: block !important;
                                        visibility: visible !important;
                                    }
                                    #print-area {
                                        position: absolute;
                                        left: 0;
                                        top: 0;
                                        width: 100%;
                                        display: flex !important;
                                        flex-direction: column !important;
                                    }
                                    tr, section, .space-y-3, .border-t {
                                        page-break-inside: avoid !important;
                                        break-inside: avoid !important;
                                    }
                                }
                            `}</style>

                            {/* Header: Branded block */}
                            <div className="border-b-2 border-[#007CFF] pb-6 flex items-start justify-between">
                                <div className="space-y-2">
                                    <div className="flex items-center gap-2">
                                        <ApplicationLogo variant="horizontal" className="h-10 w-auto" />
                                    </div>
                                    <h1 className="text-xl font-extrabold text-slate-850 tracking-tight uppercase">
                                        Pipeline Compliance & Velocity Report
                                    </h1>
                                    <p className="text-[10px] font-bold text-[#007CFF] tracking-wider uppercase">
                                        System-Generated Production Release Archive
                                    </p>
                                </div>
                                <div className="text-right text-xs text-slate-500 font-mono space-y-0.5">
                                    <p>Report ID: #{activePrintReport.id}</p>
                                    <p>Date: {new Date(activePrintReport.created_at).toLocaleDateString()}</p>
                                    <p>Status: ARCHIVED</p>
                                </div>
                            </div>

                            {/* Metadata Grid */}
                            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 p-4 rounded-xl bg-slate-50 border border-slate-105 text-xs">
                                <div>
                                    <span className="block text-[10px] text-slate-400 font-bold uppercase tracking-wider">Report Name</span>
                                    <span className="font-bold text-slate-800 truncate block mt-0.5" title={activePrintReport.name}>
                                        {activePrintReport.name}
                                    </span>
                                </div>
                                <div>
                                    <span className="block text-[10px] text-slate-400 font-bold uppercase tracking-wider">Scope Type</span>
                                    <span className="font-bold text-slate-800 block mt-0.5 uppercase">
                                        {activePrintReport.type}
                                    </span>
                                </div>
                                <div>
                                    <span className="block text-[10px] text-slate-400 font-bold uppercase tracking-wider">Target Object</span>
                                    <span className="font-bold text-[#007CFF] block mt-0.5">
                                        {activePrintReport.target_name}
                                    </span>
                                </div>
                                <div>
                                    <span className="block text-[10px] text-slate-400 font-bold uppercase tracking-wider">Generated By</span>
                                    <span className="font-bold text-slate-800 block mt-0.5">
                                        {activePrintReport.created_by}
                                    </span>
                                </div>
                            </div>

                            {/* Metrics Section */}
                            <div className="space-y-3">
                                <h3 className="text-xs font-black uppercase text-[#007CFF] tracking-wider font-heading">Metrics Summary</h3>
                                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                                    <div className="border border-slate-200 rounded-xl p-4 text-center">
                                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Total Tasks</p>
                                        <p className="text-2xl font-black text-slate-800 mt-1">{activePrintReport.metrics?.total_tasks ?? 0}</p>
                                    </div>
                                    <div className="border border-slate-200 rounded-xl p-4 text-center">
                                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Completed</p>
                                        <p className="text-2xl font-black text-emerald-600 mt-1">{activePrintReport.metrics?.completed_tasks ?? 0}</p>
                                    </div>
                                    {activePrintReport.metrics?.completion_rate !== undefined && (
                                        <div className="border border-slate-200 rounded-xl p-4 text-center">
                                            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Completion Rate</p>
                                            <p className="text-2xl font-black text-[#007CFF] mt-1">{activePrintReport.metrics.completion_rate}%</p>
                                        </div>
                                    )}
                                    {activePrintReport.metrics?.critical_tasks !== undefined && (
                                        <div className="border border-slate-200 rounded-xl p-4 text-center col-span-1">
                                            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Critical Path</p>
                                            <p className="text-2xl font-black text-rose-600 mt-1">{activePrintReport.metrics.critical_tasks}</p>
                                        </div>
                                    )}
                                </div>
                            </div>

                            {/* Detail Task Breakdown Table */}
                            {activePrintReport.metrics?.tasks_list && activePrintReport.metrics.tasks_list.length > 0 ? (
                                <div className="space-y-3">
                                    <h3 className="text-xs font-black uppercase text-[#007CFF] tracking-wider font-heading">Task Breakdown & Assignment</h3>
                                    <div className="overflow-hidden border border-slate-200 rounded-xl">
                                        <table className="w-full text-left text-xs border-collapse table-fixed">
                                            <thead>
                                                <tr className="bg-slate-50 border-b border-slate-200 text-[10px] font-bold uppercase tracking-wider text-slate-400">
                                                    <th className="px-4 py-2 w-[8%]">ID</th>
                                                    <th className="px-4 py-2 w-[38%]">Title</th>
                                                    <th className="px-4 py-2 w-[14%]">Status</th>
                                                    <th className="px-4 py-2 w-[12%]">Priority</th>
                                                    <th className="px-4 py-2 w-[8%]">Hours</th>
                                                    <th className="px-4 py-2 w-[12%]">Assignee</th>
                                                    <th className="px-4 py-2 w-[8%] text-right">Critical</th>
                                                </tr>
                                            </thead>
                                            <tbody className="divide-y divide-slate-100">
                                                {activePrintReport.metrics.tasks_list.map(t => (
                                                    <tr key={t.id} className="hover:bg-slate-50/50">
                                                        <td className="px-4 py-2 font-mono text-[10px] truncate">#{t.id}</td>
                                                        <td className="px-4 py-2">
                                                            <div className="font-semibold text-slate-800 truncate" title={t.title}>
                                                                {t.title}
                                                            </div>
                                                        </td>
                                                        <td className="px-4 py-2 truncate">
                                                            <span className="capitalize">{t.status.replace(/_/g, ' ')}</span>
                                                        </td>
                                                        <td className="px-4 py-2 truncate">
                                                            <span className="uppercase text-[9px] font-bold">{t.priority || 'MEDIUM'}</span>
                                                        </td>
                                                        <td className="px-4 py-2 font-mono truncate">{t.estimated_hours || 0}h</td>
                                                        <td className="px-4 py-2 text-slate-600 truncate">{t.assignee}</td>
                                                        <td className="px-4 py-2 text-right truncate">
                                                            {t.is_critical ? (
                                                                <span className="text-rose-600 font-extrabold">YES</span>
                                                            ) : (
                                                                <span className="text-slate-400">NO</span>
                                                            )}
                                                        </td>
                                                    </tr>
                                                ))}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            ) : (
                                <div className="p-8 text-center border border-dashed border-slate-200 rounded-xl">
                                    <p className="text-xs text-slate-400 font-semibold">No tasks included in this archive snapshot.</p>
                                </div>
                            )}

                            {/* Project Activity & Audit Timeline */}
                            {activePrintReport.metrics?.logs && activePrintReport.metrics.logs.length > 0 && (
                                <div className="space-y-3">
                                    <h3 className="text-xs font-black uppercase text-[#007CFF] tracking-wider font-heading">Project Activity &amp; Audit Timeline</h3>
                                    <div className="overflow-hidden border border-slate-200 rounded-xl bg-white">
                                        <table className="w-full text-left text-xs border-collapse">
                                            <thead>
                                                <tr className="bg-slate-50 border-b border-slate-200 text-[10px] font-bold uppercase tracking-wider text-slate-400">
                                                    <th className="px-4 py-2.5 w-1/4">Timestamp</th>
                                                    <th className="px-4 py-2.5 w-1/5">Type</th>
                                                    <th className="px-4 py-2.5">Activity Description</th>
                                                </tr>
                                            </thead>
                                            <tbody className="divide-y divide-slate-100 font-sans">
                                                {activePrintReport.metrics.logs.map((log, lIdx) => {
                                                    const formattedDate = new Date(log.timestamp.replace(/-/g, '/')).toLocaleString('en-US', {
                                                        month: 'short',
                                                        day: 'numeric',
                                                        year: 'numeric',
                                                        hour: 'numeric',
                                                        minute: 'numeric',
                                                        hour12: true
                                                     });
                                                     
                                                     const badgeStyles = {
                                                         success: 'bg-emerald-50 text-emerald-700 border-emerald-200/60 dark:bg-emerald-950/20 dark:text-emerald-450 dark:border-emerald-800/40',
                                                         warning: 'bg-amber-50 text-amber-700 border-amber-200/60 dark:bg-amber-950/20 dark:text-amber-450 dark:border-amber-800/40',
                                                         info: 'bg-blue-50 text-blue-700 border-blue-200/60 dark:bg-blue-950/20 dark:text-blue-450 dark:border-blue-800/40'
                                                     };
                                                     
                                                     const typeLabels = {
                                                         success: 'Completed',
                                                         warning: 'Under Review',
                                                         info: 'Setup'
                                                     };
                                                     
                                                     return (
                                                         <tr key={lIdx} className="hover:bg-slate-50/50">
                                                             <td className="px-4 py-2.5 text-slate-500 font-mono text-[10px]">
                                                                 {formattedDate !== 'Invalid Date' ? formattedDate : log.timestamp}
                                                             </td>
                                                             <td className="px-4 py-2.5">
                                                                 <span className={`inline-flex items-center px-2 py-0.5 rounded-full border text-[9px] font-bold uppercase tracking-wide ${badgeStyles[log.type] || badgeStyles.info}`}>
                                                                     {typeLabels[log.type] || log.type}
                                                                 </span>
                                                             </td>
                                                             <td className="px-4 py-2.5 text-slate-700 font-medium">
                                                                 {log.message}
                                                             </td>
                                                         </tr>
                                                     );
                                                 })}
                                             </tbody>
                                         </table>
                                     </div>
                                 </div>
                             )}

                            {/* Signatures & Footer block */}
                            <div className="border-t border-slate-200 pt-8 mt-12 flex flex-col md:flex-row justify-between items-start md:items-end gap-6 text-[10px] text-slate-400 font-sans">
                                <div className="max-w-md space-y-1">
                                    <p className="font-bold text-slate-700">Vaultera Labs Compliance & Governance Seal</p>
                                    <p className="leading-relaxed">
                                        This document represents an immutable snapshot of project task logs and work schedules archived for compliance, auditing, and sprint efficiency reports.
                                    </p>
                                </div>
                                <div className="flex gap-12 text-center shrink-0">
                                    <div className="space-y-4">
                                        <div className="w-32 border-b border-slate-400 h-8" />
                                        <span className="block font-bold text-slate-700">Project Architect</span>
                                    </div>
                                    <div className="space-y-4">
                                        <div className="w-32 border-b border-slate-400 h-8" />
                                        <span className="block font-bold text-slate-700">Release Engineer</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    </div>
                </div>
            )}
        </TenantLayout>
    );
}
